import { esc } from '../../core/utils.js';

const labels = { habit: 'Habits', goal: 'Finite Goals', skill: 'Infinite Skills', personal: 'Personal Habits' };
export const label = type => labels[type] || type;

export function view(state) {
  const items = state.config.items;
  const rows = items.length ? items.map(item => `<div class="row"><div><div class="item-name">${esc(item.name)} ${item.archived ? '<span class="pill">archived</span>' : ''}</div><div class="muted">${label(item.type)} · ${esc(item.type === 'habit' || item.type === 'personal' ? item.method : item.type === 'goal' ? item.unit : 'custom')}</div></div><div class="control">${item.archived ? '' : `<button class="btn" data-edit="${esc(item.id)}">Edit</button><button class="btn danger" data-archive="${esc(item.id)}">Remove</button>`}</div></div>`).join('') : '<div class="empty">No tracker items yet.</div>';
  return `<section class="section"><h2>Manage tracker</h2><div class="section-body"><div class="actions"><button class="btn primary" data-add="habit">+ Habit</button><button class="btn" data-add="goal">+ Finite Goal</button><button class="btn" data-add="skill">+ Infinite Skill</button><button class="btn" data-add="personal">+ Personal Habit</button></div>${rows}</div></section><section class="section"><h2>Vault & backups</h2><div class="section-body"><div class="grid"><div class="field"><label>Export format</label><select id="exportFormat"><option value="encrypted">Encrypted vault (recommended)</option><option value="plain">Plain-text JSON</option></select><div class="hint">Plain-text files can be read by anyone who has the file.</div></div><div class="field"><label>Auto-lock minutes</label><input id="lockMin" type="number" min="1" value="${state.config.lockMinutes}"></div></div><div class="actions"><button class="btn" data-action="fullExport">Full Backup</button><button class="btn" data-action="recordsExport">Records Export</button><label class="btn">Import <input id="import" type="file" hidden accept=".vault,.json,application/json,application/octet-stream"></label></div></div></section>`;
}
